FROM debian:bullseye-slim

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends iproute2 dnsutils stress-ng\
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*
