FROM debian:bookworm-slim

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends iproute2 dnsutils stress-ng util-linux\
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*
