FROM debian:bullseye-slim

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends iproute2\
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/sbin/ip"]
